# Change these first
owner: VI-Software # Your GitHub organization or username, where this repository lives
repo: launcher-status # The name of this repository

sites:
  - name: VI Software API
    url: https://api.visoftware.tech/services/servers
    expectedStatusCodes:
      - 200  
  - name: VI Software Yggdrasil Auth Server
    url: https://authserver.visoftware.tech
    expectedStatusCodes:
      - 200
  - name: VI Software CDN
    url: https://cdn.visoftware.tech
    expectedStatusCodes:
      - 200        
  - name: VI Software PUF
    url: https://puf.visoftware.tech
    expectedStatusCodes:
      - 200     
  - name: VI Software PUF Nightly
    url: https://nightly-puf.visoftware.tech
    expectedStatusCodes:
      - 200        
  - name: VI Software Skin Rendering Service
    url: https://skins.visoftware.tech
    expectedStatusCodes:
      - 200
  - name: VI Software Docs
    url: https://docs.visoftware.tech
    expectedStatusCodes:
      - 200       
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.visoftware.tech
  # baseUrl: /launcher-status
  logoUrl: https://api.visoftware.tech/logo/vis-logo-nl.png
  name: VI Software Status
  introTitle: "Página oficial de estados de VI Software"
  introMessage: VI Software is neither affiliated with nor endorsed by Mojang AB, Xbox Game Studios, or Microsoft Corporation
  navbar:
    - title: Portal
      href: https://visoftware.tech
    - title: Panel de Usuario Final (PUF)
      href: https://puf.visoftware.tech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
